[package]
name = "poc-golang-vue2"
version = "2.0.0"
authors = ["Ninjapiraatti"]
edition = "2018"

[dependencies]
actix-files = "0.5.0"
actix-session = "0.4.1"
actix-identity = "0.3"
actix-web = "3.3"
actix-rt = "1.1"
env_logger = "0.8"
dotenv = "0.15"

[dev-dependencies]
actix-rt = "1.1"
